name: 'Actions Sentinel'
description: 'A security-focused tool for evaluating and managing GitHub Actions'
author: 'tdupoiron'

inputs:
  actions:
    description: 'Comma-separated list of actions to evaluate (e.g., "actions/checkout@v3,actions/setup-node@v3")'
    required: true
  organization:
    description: 'GitHub organization name'
    required: true
  github-token:
    description: 'GitHub token with admin:org permissions'
    required: true
    default: ${{ github.token }}

outputs:
  result:
    description: 'Detailed results of the actions evaluation'
  status:
    description: 'Status of the evaluation (success/failure)'
  details:
    description: 'Additional details about the evaluation process'

runs:
  using: 'node16'
  main: 'dist/index.js'