name: Build

on:
  push:
    paths:
      - 'action/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for checkout and pushing changes
      id-token: write   # Required for GitHub App token generation
    steps:

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ACTIONS_SENTINEL_APP_ID }}
          private-key: ${{ secrets.ACTIONS_SENTINEL_APP_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      
      - name: Install dependencies
        working-directory: ./action
        run: npm ci
      
      - name: Build
        working-directory: ./action
        run: npm run build
      
      - name: Validate Build
        working-directory: ./action
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Error: Build output not found"
            exit 1
          fi

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Commit dist
        run: |
          git config --local user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git config --local user.name "sentinel"
          git add action/dist
          git commit -m "chore: update dist" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
