name: Build

on:
  push:
    paths:
      - 'action/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: action/package-lock.json
      
      - name: Install dependencies
        run: |
          npm ci
          cd action && npm ci
      
      - name: Build
        working-directory: ./action
        run: npm run build
      
      - name: Validate Build
        working-directory: ./action
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Error: Build output not found"
            exit 1
          fi
      
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ACTIONS_SENTINEL_APP_ID }}
          private-key: ${{ secrets.ACTIONS_SENTINEL_APP_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Commit dist
        run: |
          git config --local user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git config --local user.name "${{ steps.generate-token.outputs.app-slug }}[bot]"
          git add action/dist
          git commit -m "chore: update dist" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
