name: Actions Whitelist PR Integration

on:
  pull_request:
    paths:
      - 'whitelist/actions.yml'
    types: [closed]

jobs:
  integrate-whitelist:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ACTIONS_SENTINEL_APP_ID }}
          private-key: ${{ secrets.ACTIONS_SENTINEL_APP_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install yaml

      - name: Read and parse whitelist
        id: whitelist
        uses: actions/github-script@v7
        with:
          script: |
            const yaml = require('yaml');
            const fs = require('fs');
            
            // Read the whitelist file
            const whitelistContent = fs.readFileSync('whitelist/actions.yml', 'utf8');
            const whitelist = yaml.parse(whitelistContent);
            
            // Get allowed actions and join them with commas
            const allowedActions = whitelist.allowedActions.map(action => action.name).join(',');
            return allowedActions;
          result-encoding: string

      - name: Update action restrictions
        uses: ./action
        with:
          actions: ${{ steps.whitelist.outputs.result }}
          organization: ${{ github.repository_owner }}
          github-token: ${{ steps.generate-token.outputs.token }}
